### PR TITLE
fix(frontend): handle invalid jwt response from backend

### LINKED ISSUE #2349: [bug] stale jwt key not handled
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

After having a hosted Omni tab open for some time, it redirected to (domain)/authenticate?flow=frontend&redirect=/. I chose the login in the Authenticate UI Access dialog. A popup of "Failed to confirm public key" pops up.

### Expected Behavior

It should redirect to the authentication source (Auth0 for a Google account in the hosted instance) to renew that authentication information.

### Steps To Reproduce

1. Leave the Omni instance idle for some time on the dashboard.

### What browsers are you seeing the problem on?

Microsoft Edge

### Anything else?

Repeating the experience seemed like similar behavior occured but sourced in a JSON response getting mishandled and put into the JWT popup. The way screens/dialogs are titled, it seems like it's trying to redirect but it's not doing so consistently or reliably.

Hosted Omni is currently 1.4.9

### PR DESCRIPTION
**Pull request by Slessi**
If the backend returns an invalid jwt error, the frontend must re-trigger the authentication flow

Closes #2349

### CODE REVIEW

File: frontend/src/views/omni/Auth/Authenticate.vue [hunk 1]
```diff
@@ -182,23 +182,8 @@ const generatePublicKey = async (identity: string) => {
   await router.replace({ path: !redirect.startsWith('/') ? '/' : redirect })
 }
 
-let renewIdToken = false
-
 const confirmPublicKey = async (publicKeyId: string, keyPair?: CryptoKeyPair) => {
   try {
-    // If the JWT validation has failed on the backend at the moment of clicking "Login", get a new ID token from Auth0 on the next click.
-    // This way, the user will not have to reload the page after validating their email - they can simply click "Login" again to get in.
```
Comment (Slessi) [inline frontend/src/views/omni/Auth/Authenticate.vue:190]: User was stuck in an "invalid JWT" loop because of this.

Im not sure about the original thinking behind this, but pretty sure we cant support this flow. If there is something wrong with the token, we have to re-auth, to meet our security policies.

Even if not, this isn't a nice flow:

- Click login
- Login error
- Click login
- Login accepted

Should've just worked the first time, if user interaction wasn't required to fix the problem
