### PR TITLE
fix: add validation of k8s version

### LINKED ISSUE #1284: [bug] Cluster template sync allows k8s upgrades across > 1 minor version
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

- UI only allows upgrades to the latest patch of the next minor version (e.g., from `1.28.15` to `1.29.15`).
- Cluster templates allow setting higher unsupported minor versions (e.g., `1.30.5`), which bypasses this protection.
- Sync fails only if the version is invalid (e.g., `1.29.16`).

### Expected Behavior

Cluster templates should enforce the same Kubernetes version upgrade restrictions as the UI.

### Steps To Reproduce

`omnictl cluster template export <cluster> -o cluster-template.yaml`

update k8s version > 2 minor versions

`omnictl cluster template sync -f cluster-template.yaml`

cluster will start upgrading to unsupported version

### What browsers are you seeing the problem on?

_No response_

### Anything else?

I believe downgrading also possible through this

### PR DESCRIPTION
**Pull request by shanduur**
We lack K8s upgrade path validation - this allowed upgrades using API to jump over minor Kubernetes releases, which is not a supported upgrade pattern. This PR adds new validation and reworks some of the tests.

Fixes #1284

### CODE REVIEW

File: internal/backend/runtime/omni/state_validation.go [hunk 1]
```diff
@@ -156,6 +167,7 @@ func clusterValidationOptions(st state.State, etcdBackupConfig config.EtcdBackup
 
 			skipTalosVersion := existingRes.TypedSpec().Value.TalosVersion == newRes.TypedSpec().Value.TalosVersion
 			skipKubernetesVersion := existingRes.TypedSpec().Value.KubernetesVersion == newRes.TypedSpec().Value.KubernetesVersion
+			// skipKubernetesVersion := skipTalosVersion && existingRes.TypedSpec().Value.KubernetesVersion == newRes.TypedSpec().Value.KubernetesVersion
```
Comment (shanduur) [inline internal/backend/runtime/omni/state_validation.go]: I'm not sure about this. There was a test case that confirmed that previous behavior was desired, however as we discussed with @smira this should only be true when the Talos version check is skipped.

Comment (smira) [reply internal/backend/runtime/omni/state_validation.go]: so my reasoning is the following: if I trigger a Talos upgrade which will make Kubernetes version not compatible with new Talos, we should ignore such request

Comment (Unix4ever) [reply internal/backend/runtime/omni/state_validation.go]: I'm struggling to understand the reason behind this condition.
I think it's fine to drop it.

The validation should check if the new Talos version (or current if not changed) supports the new Kubernetes version (or current).

Comment (Unix4ever) [reply internal/backend/runtime/omni/state_validation.go]: > so my reasoning is the following: if I trigger a Talos upgrade which will make Kubernetes version not compatible with new Talos, we should ignore such request

Ahh, yeah. Now I remember. This check is probably required there.
We need to keep validating the kubernetes version even if it's not changed when we try to update Talos.

Comment (shanduur) [reply internal/backend/runtime/omni/state_validation.go]: I adjusted the code to include the check suggested by @smira, thanks!

**Review by Unix4ever — APPROVED** [review]
