### PR TITLE
fix: add nonce for userpilot scripts

### LINKED ISSUE #1879: [feature] Allow userpilot script to run
### Problem Description

When Omni is started with `--user-pilot-app-token` and a user opts in to allowing cookies the script needs to be able to run with `unsafe-inline`

### Solution

The script needs

```
script-src   'self' https://*.userpilot.io 'unsafe-inline';
```
https://docs.userpilot.com/developer/security/csp

### Alternative Solutions

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by Slessi**
Update CSP to include nonce for userpilot scripts without enabling 'unsafe-inline'.

Fixes #1879

### CODE REVIEW

File: internal/frontend/handler.go [hunk 1]
```diff
@@ -107,13 +108,20 @@ func (handler *StaticHandler) serveFile(w http.ResponseWriter, r *http.Request,
...
+			nonce := "i9o9123rlm"
+
+			w.Header().Set("Content-Security-Policy",
+				"upgrade-insecure-requests"+
+					fmt.Sprintf(";default-src 'self' 'nonce-%s'", nonce)+
+					";img-src * data:"+
+					";connect-src 'self' https://*.auth0.com https://*.userpilot.io wss://*.userpilot.io"+
+					";font-src 'self' data:"+
+					fmt.Sprintf(";style-src 'self' 'nonce-%s' data: https://fonts.googleapis.com https://fonts.gstatic.com", nonce)+
+					";frame-src https://*.auth0.com",
```
Comment (Slessi) [inline internal/frontend/handler.go:134]: I shuffled this a bit to have one rule per line for readability

File: internal/frontend/handler.go [hunk 2]
```diff
@@ -107,13 +108,20 @@ func (handler *StaticHandler) serveFile(w http.ResponseWriter, r *http.Request,
...
 			w.Header().Set("Cache-Control", fmt.Sprintf("public, max-age=%d, immutable", handler.maxAgeSec))
+			http.ServeContent(w, r, file.Name(), handler.modTime, file)
 		} else {
 			w.Header().Set("Referrer-Policy", "strict-origin-when-cross-origin")
 
-			w.Header().Set("Content-Security-Policy", "default-src 'self' https://*.userpilot.io; img-src * data: ; "+
-				";connect-src 'self' https://*.auth0.com https://*.userpilot.io wss://*.userpilot.io ;font-src 'self' data: "+
-				";style-src 'self' 'unsafe-inline' https://fonts.googleapis.com data: ;upgrade-insecure-requests;"+
-				";frame-src https://*.auth0.com",
+			nonce := "i9o9123rlm"
```
Comment (Unix4ever) [inline internal/frontend/handler.go]:
```suggestion
			b := make([]byte, 10)
			if _, err := rand.Read(b); err != nil {
				writeHTTPError(w, fmt.Errorf("failed to read random bytes: %w", err))
				
				return
			}

			nonce := base62.EncodeToString(b)
```

**Review by Unix4ever — APPROVED** [review]
